### ISSUE TITLE
Typo in train.py

### ISSUE THREAD

**Issue by michaeljehan** [Rui1521/Turbulent-Flow-Nets#1]
<img width="598" alt="Screen Shot 2021-10-18 at 1 54 23 AM" src="https://user-images.githubusercontent.com/68639241/137640976-1d75fb5f-f624-4662-b7c2-7bd2d40b1a48.png">
It seems that there is a typo in line 34, could you tell me what the correct line actually is?
Thanks

**Comment by Rui1521** [comment]
It's y.shape[-1]. Thanks!
